Repository LBNL-UCB-STI/beam, pull requests merged in 2019-08, with the labels that each got.

#2027 Warmstart: Compress csv files and dump MATSim stuff in the end of every iteration
  src/main/scala/beam/sim/BeamSim.scala
  src/main/scala/beam/sim/BeamWarmStart.scala
  test/input/sf-light/sf-light-25k-warmstart.conf
  test/input/sf-light/sf-light-25k.conf
Labels: warmstart

#2040 rjf/#2038-beamville-parking-config-bug
  src/main/scala/beam/agentsim/infrastructure/charging/ChargingPointType.scala
  src/test/scala/beam/agentsim/infrastructure/charging/ChargingPointTypeSpec.scala
  test/input/beamville/parking/taz-parking-default.csv
  test/input/beamville/parking/taz-parking-empty.csv
  test/input/beamville/parking/taz-parking-expensive-old.csv
  test/input/beamville/parking/taz-parking-expensive.csv
  test/input/beamville/parking/taz-parking-limited.csv
  test/input/beamville/parking/taz-parking.csv
Labels: bug

#1676 smart analysis misc.
  src/main/R/beam-utilities.R
  src/main/R/smart-analysis.R
  test/input/sf-light/urbansim-10k.conf
Labels: review

#1706 test summary stats (vehicle miles traveled)
  src/test/scala/beam/analysis/plots/VehicleMilesTraveledAnalysisSpec.scala
Labels: review

#1682 Project: distLatLon2Meters should use convert coordinates from WGS to UTM and use distUTMInMeters
  src/main/java/beam/analysis/PathTraversalSpatialTemporalTableGenerator.java
  src/main/scala/beam/replanning/utilitybased/ChangeModeForTour.scala
  src/main/scala/beam/router/TransitInitializer.scala
  src/main/scala/beam/sim/common/GeoUtils.scala
Labels: review

#2139 make dummy walk trip start at the time of the ridehail request
  src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
Labels: bug
