Repository LBNL-UCB-STI/beam, pull requests merged in 2019-03, with the labels that each got.

#1368 print ridehail manager state only once when stuck
  src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala
Labels: review

#1372 Fix broken master branch due to fmt
  src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala
Labels: review

#1370 Cs/unstuck 2
  src/main/bash/deploy-examples.sh
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
  src/main/scala/beam/agentsim/agents/ridehail/allocation/PoolingAlonsoMora.scala
  src/main/scala/beam/agentsim/agents/ridehail/allocation/RideHailResourceAllocationManager.scala
  src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala
Labels: review

#1374 change deadheading graph title and relabel legend
  src/main/java/beam/analysis/plots/DeadHeadingAnalysis.java
Labels: review

#1373 Sync competition with master #1: PlansSamplerApp and dependencies
  src/main/scala/beam/utils/BeamVehicleUtils.scala
  src/main/scala/beam/utils/plan/sampling/PlansSamplerApp.scala
Labels: review

#1379 Zn/#1247 vott modifications
  src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
  src/main/resources/beam-template.conf
  src/main/scala/beam/agentsim/agents/PersonAgent.scala
  src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceDriveIfAvailable.scala
  src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceLCCM.scala
  src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogit.scala
  src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceRideHailIfAvailable.scala
  src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceTransitIfAvailable.scala
  src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceUniformRandom.scala
  src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala
  src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
  src/main/scala/beam/agentsim/agents/modalbehaviors/ModeChoiceCalculator.scala
  src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala
  src/main/scala/beam/scoring/BeamScoringFunctionFactory.scala
  src/main/scala/beam/sim/BeamServices.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
  src/main/scala/beam/sim/population/PopulationAttributes.scala
  src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
  test/input/beamville/beam.conf
Labels: review

#1360 write matsim network out as csv
  src/main/scala/beam/utils/NetworkXmlToCSV.scala
Labels: review

#1296 Vehicle Energy rate from data file
  build.gradle
  src/main/java/beam/analysis/PathTraversalSpatialTemporalTableGenerator.java
  src/main/java/beam/analysis/plots/FuelUsageAnalysis.java
  src/main/java/beam/physsim/jdeqsim/AgentSimPhysSimInterfaceDebugger.java
  src/main/resources/beam-template.conf
  src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
  src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
  src/main/scala/beam/agentsim/agents/vehicles/BeamVehicleType.scala
  src/main/scala/beam/agentsim/agents/vehicles/EnergyEconomyAttributes.scala
  src/main/scala/beam/agentsim/agents/vehicles/VehicleEnergy.scala
  src/main/scala/beam/agentsim/events/PathTraversalEvent.scala
  src/main/scala/beam/router/r5/R5RoutingWorker.scala
  src/main/scala/beam/sim/BeamServices.scala
  src/main/scala/beam/sim/common/Range.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
  src/main/scala/beam/utils/BeamVehicleUtils.scala
  src/main/scala/beam/utils/ScenarioComparator.scala
  src/main/scala/beam/utils/matsim_conversion/MatsimConversionTool.scala
  src/main/scala/beam/utils/plan/sampling/PlansSamplerApp.scala
  src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
  src/test/scala/beam/agentsim/agents/RideHailAgentSpec.scala
  src/test/scala/beam/agentsim/agents/ridehail/graph/FuelUsageStatsGraphSpec.scala
  src/test/scala/beam/agentsim/agents/vehicles/VehicleEnergyTest.scala
  src/test/scala/beam/router/TransitInitializerSpec.scala
  test/input/beamville/beam.conf
  test/input/beamville/linkToGradePercent.csv
  test/input/beamville/r5/tolls.dat
  test/input/beamville/test-data/beamville.events.xml
  test/input/beamville/vehicle-energy/default-energy-primary.csv
  test/input/beamville/vehicle-energy/default-energy-secondary.csv
  test/input/beamville/vehicleTypes.csv
  test/input/beamville/vehicles.csv
  test/input/sf-light/linkToGradePercent.csv
  test/input/sf-light/sf-light-0.5k.conf
  test/input/sf-light/sf-light-10k.conf
  test/input/sf-light/sf-light-1k.conf
  test/input/sf-light/sf-light-2.5k.conf
  test/input/sf-light/sf-light-25k.conf
  test/input/sf-light/sf-light-5k.conf
  test/input/sf-light/sf-light.conf
  test/input/sf-light/vehicle-energy/default-energy-primary.csv
  test/input/sf-light/vehicle-energy/default-energy-secondary.csv
  test/input/sf-light/vehicleTypes.csv
Labels: review

#1380 Skimmer and HH CAV Improvements
  src/main/scala/beam/agentsim/agents/MobilityRequest.scala
  src/main/scala/beam/agentsim/agents/PersonAgent.scala
  src/main/scala/beam/agentsim/agents/Population.scala
  src/main/scala/beam/agentsim/agents/household/FastHouseholdCAVScheduling.scala
  src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala
  src/main/scala/beam/agentsim/agents/household/HouseholdCAVScheduling.scala
  src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
  src/main/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHail.scala
  src/main/scala/beam/agentsim/agents/ridehail/AsyncAlonsoMoraAlgForRideHail.scala
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
  src/main/scala/beam/agentsim/agents/ridehail/allocation/PoolingAlonsoMora.scala
  src/main/scala/beam/agentsim/agents/ridehail/allocation/RideHailResourceAllocationManager.scala
  src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala
  src/main/scala/beam/router/BeamSkimmer.scala
  src/main/scala/beam/router/Modes.scala
  src/main/scala/beam/scoring/BeamScoringFunctionFactory.scala
  src/main/scala/beam/sim/BeamHelper.scala
  src/main/scala/beam/sim/BeamMobsim.scala
  src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
  src/test/scala/beam/agentsim/agents/household/FastHouseholdCAVSchedulingSpec.scala
  src/test/scala/beam/agentsim/agents/household/HouseholdCAVSchedulingTest.scala
  src/test/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHailSpec.scala
  src/test/scala/beam/agentsim/agents/ridehail/AsyncAlonsoMoraAlgForRideHailSpec.scala
  src/test/scala/beam/integration/MultinomialCustomConfigSpec.scala
  src/test/scala/beam/integration/SingleModeSpec.scala
  test/input/sf-light/sf-light-10k.conf
  test/input/sf-light/sf-light-1k.conf
Labels: review

#1385 Leg Duration Fixes and gradient file fallback
  src/main/resources/beam-template.conf
  src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogit.scala
  src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala
  src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
  src/main/scala/beam/agentsim/agents/vehicles/VehicleEnergy.scala
  src/main/scala/beam/router/model/BeamLeg.scala
  src/main/scala/beam/router/model/BeamPath.scala
  src/main/scala/beam/router/r5/R5RoutingWorker.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
  src/main/scala/beam/sim/population/PopulationAttributes.scala
  src/test/scala/beam/agentsim/agents/household/HouseholdCAVSchedulingTest.scala
  src/test/scala/beam/router/TimeDependentRoutingSpec.scala
  src/test/scala/beam/router/TollRoutingSpec.scala
  src/test/scala/beam/router/WarmStartRoutingSpec.scala
Labels: review

#1387 Cs/quick patch
  src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala
  src/main/scala/beam/router/model/BeamLeg.scala
Labels: review

#1338 Scenario: Ability to load scenario from parquet
  build.gradle
  src/main/resources/beam-template.conf
  src/main/resources/logback.xml
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
  src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala
  src/main/scala/beam/sim/BeamHelper.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
  src/main/scala/beam/sim/population/PopulationAdjustment.scala
  src/main/scala/beam/sim/vehicles/DefaultVehiclesAdjustment.scala
  src/main/scala/beam/utils/ParquetReader.scala
  src/main/scala/beam/utils/ScenarioComparator.scala
  src/main/scala/beam/utils/ScenarioReaderCsv.scala
  src/main/scala/beam/utils/plan/sampling/AvailableModeUtils.scala
  src/main/scala/beam/utils/scenario/InputType.scala
  src/main/scala/beam/utils/scenario/Models.scala
  src/main/scala/beam/utils/scenario/ScenarioLoader.scala
  src/main/scala/beam/utils/scenario/ScenarioSource.scala
  src/main/scala/beam/utils/scenario/ScenarioWriter.scala
  src/main/scala/beam/utils/scenario/matsim/MatsimScenarioReader.scala
  src/main/scala/beam/utils/scenario/matsim/MatsimScenarioSource.scala
  src/main/scala/beam/utils/scenario/urbansim/CsvScenarioReader.scala
  src/main/scala/beam/utils/scenario/urbansim/DataExchange.scala
  src/main/scala/beam/utils/scenario/urbansim/ParquetScenarioReader.scala
  src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioReader.scala
  src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala
  src/test/scala/beam/utils/ParquetReaderTest.scala
  src/test/scala/beam/utils/scenario/urbansim/ParquetUrbanSimScenarioReaderTest.scala
  test/test-resources/test.parquet
Labels: review

#1388 Cs/sample vehicles
  src/main/R/sample-urbansim.R
  src/main/scala/beam/agentsim/agents/vehicles/BeamVehicleType.scala
  src/main/scala/beam/sim/vehicles/UniformVehiclesAdjustment.scala
  src/main/scala/beam/sim/vehicles/VehiclesAdjustment.scala
  src/main/scala/beam/utils/BeamVehicleUtils.scala
  src/main/scala/beam/utils/scenario/matsim/MatsimScenarioReader.scala
  test/input/beamville/vehicleTypes.csv
  test/input/sf-light/urbansim-1k.conf
  test/input/sf-light/urbansim/1k/buildings.csv
  test/input/sf-light/urbansim/1k/households.csv
  test/input/sf-light/urbansim/1k/parcel_attr.csv
  test/input/sf-light/urbansim/1k/persons.csv
  test/input/sf-light/urbansim/1k/plans.csv
  test/input/sf-light/urbansim/1k/units.csv
  test/input/sf-light/vehicleTypes.csv
Labels: review

#1375 make BeamAgentScheduler.scheduleMonitorTask interval configurable
  src/main/resources/beam-template.conf
  src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
Labels: review

#1362 add exception for illegal config path location
  src/main/scala/beam/sim/BeamHelper.scala
Labels: review

#1384 refactor/bug fix: beam/utils/NetworkXmlToCSV
  src/main/scala/beam/utils/NetworkXmlToCSV.scala
  src/test/scala/beam/utils/NetworkXmlToCsvSpec.scala
Labels: review

#1376 Sync competition with master #2: Renamed class MotorizedVehicleMilesTraveledAnalysis and enumeration
  src/main/java/beam/analysis/StatsFactory.java
  src/main/java/beam/analysis/summary/VehicleMilesTraveledAnalysis.java
  src/main/scala/beam/sim/BeamServices.scala
Labels: review

#1393 create root graph for replanning count mode choice
  src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
Labels: review

#1354 add reference normalized to 1 in realized mode
  src/main/java/beam/analysis/StatsFactory.java
  src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
  src/test/java/beam/analysis/plots/RealizedModeGraphTest.java
  src/test/scala/beam/agentsim/agents/ridehail/graph/RealizedModeStatsGraphSpec.scala
Labels: review

#1416 Cs/ridehail price adjustments
  src/main/scala/beam/agentsim/agents/PersonAgent.scala
  src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala
  src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
  src/main/scala/beam/router/BeamRouter.scala
  src/main/scala/beam/router/RouteHistory.scala
  src/main/scala/beam/router/model/BeamLeg.scala
  src/main/scala/beam/router/model/EmbodiedBeamLeg.scala
  src/main/scala/beam/router/r5/R5RoutingWorker.scala
  src/main/scala/beam/sim/BeamMobsim.scala
  src/main/scala/beam/sim/common/GeoUtils.scala
  src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
  src/test/scala/beam/analysis/plots/PersonCostAnalysisSpec.scala
Labels: review

#1355 Make filenames config consistent 4ci (Issue 1364) [master]
  src/main/java/beam/agentsim/agents/choice/logit/LatentClassChoiceModel.scala
  src/main/java/beam/analysis/plots/GraphsStatsAgentSimEventsListener.java
  src/main/java/beam/analysis/plots/ModeChosenAnalysis.java
  src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
  src/main/resources/beam-template.conf
  src/main/scala/beam/agentsim/agents/vehicles/VehicleEnergy.scala
  src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
  src/main/scala/beam/router/osm/TollCalculator.scala
  src/main/scala/beam/router/r5/R5RoutingWorker.scala
  src/main/scala/beam/sim/BeamHelper.scala
  src/main/scala/beam/sim/BeamServices.scala
  src/main/scala/beam/sim/RideHailFleetInitializer.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
  src/main/scala/beam/utils/ConfigConsistencyComparator.scala
  src/main/scala/beam/utils/ScenarioComparator.scala
  src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
  src/test/scala/beam/agentsim/agents/ridehail/RideHailSurgePricingManagerSpec.scala
  src/test/scala/beam/agentsim/infrastructure/ZonalParkingManagerSpec.scala
  src/test/scala/beam/integration/ParkingSpec.scala
  src/test/scala/beam/router/TransitInitializerSpec.scala
  test/input/beamville/beam.conf
  test/input/common/matsim.conf
  test/input/equil-square/equil-0.001k.conf
  test/input/sf-light/sf-light-0.5k.conf
  test/input/sf-light/sf-light-10k.conf
  test/input/sf-light/sf-light-1k.conf
  test/input/sf-light/sf-light-2.5k.conf
  test/input/sf-light/sf-light-25k.conf
  test/input/sf-light/sf-light-5k.conf
  test/input/sf-light/sf-light.conf
Labels: review

#1422 StuckFinder: Stuck agent due to exceed number of messages is logged only once
  src/main/scala/beam/utils/StuckFinder.scala
  src/test/scala/beam/utils/StuckFinderSpec.scala
Labels: review

#1428 destTaz with the same code as origTaz - bug fixed
  src/main/scala/beam/router/BeamSkimmer.scala
Labels: review

#1426 Beam skimmer cleanup 4ci
  src/main/scala/beam/router/BeamSkimmer.scala
Labels: review

#1430 Load previous beam skimmer if warmup is enabled
  src/main/scala/beam/router/BeamSkimmer.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
  src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
  src/test/scala/beam/agentsim/agents/household/FastHouseholdCAVSchedulingSpec.scala
  src/test/scala/beam/agentsim/agents/household/HouseholdCAVSchedulingTest.scala
  src/test/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHailSpec.scala
  src/test/scala/beam/agentsim/agents/ridehail/AsyncAlonsoMoraAlgForRideHailSpec.scala
  src/test/scala/beam/integration/SingleModeSpec.scala
Labels: review

#1432 Route history clean up code
  src/main/scala/beam/router/RouteHistory.scala
Labels: review

#1436 keep same color code for realized mode and reference realized mode
  src/main/java/beam/analysis/plots/GraphUtils.java
Labels: review

#1434 replaced lazyLogging with ExponentialLazyLogging
  src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala
Labels: review

#1443 add config param for pooledToRegularRideCostRatio
  src/main/resources/beam-template.conf
  src/main/scala/beam/router/BeamSkimmer.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
Labels: review

#1446 print complete exception for stats collectors
  src/main/java/beam/analysis/plots/GraphsStatsAgentSimEventsListener.java
Labels: review

#1451 fixed beam.inputDirectory resolution issue.
  src/main/scala/beam/utils/ConfigConsistencyComparator.scala
Labels: review

#1452 update missing filePath configs
  test/input/equil-square/equil-0.001k.conf
  test/input/sf-light/rideHailFleet.csv
  test/input/sf-light/urbansim-100k.conf
  test/input/sf-light/urbansim-10k-test-energy.conf
  test/input/sf-light/urbansim-10k.conf
  test/input/sf-light/urbansim-1k.conf
  test/input/sf-light/urbansim-250k.conf
Labels: review

#1438 SummaryStats compatible with Windows OS
  src/main/scala/beam/sim/BeamSim.scala
Labels: review

#1437 Project: Fix minor memory leaks
  src/main/java/beam/analysis/summary/PersonCostAnalysis.java
  src/main/java/beam/analysis/summary/VehicleTravelTimeAnalysis.java
Labels: review

#1455 fix matsim config builder name
  src/main/scala/beam/router/r5/R5RoutingWorker.scala
  src/main/scala/beam/sim/BeamHelper.scala
  src/main/scala/beam/sim/config/MatSimBeamConfigBuilder.scala
  src/main/scala/beam/utils/ScenarioComparator.scala
  src/test/scala/beam/agentsim/agents/GenericEventsSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
  src/test/scala/beam/agentsim/agents/RideHailAgentSpec.scala
  src/test/scala/beam/agentsim/agents/household/FastHouseholdCAVSchedulingSpec.scala
  src/test/scala/beam/agentsim/agents/household/HouseholdCAVSchedulingTest.scala
  src/test/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHailSpec.scala
  src/test/scala/beam/agentsim/agents/ridehail/AsyncAlonsoMoraAlgForRideHailSpec.scala
  src/test/scala/beam/agentsim/agents/ridehail/RideHailPassengersEventsSpec.scala
  src/test/scala/beam/agentsim/agents/ridehail/graph/GraphRunHelper.scala
  src/test/scala/beam/integration/CarSharingSpec.scala
  src/test/scala/beam/integration/DriveTransitSpec.scala
  src/test/scala/beam/integration/LCCMSpec.scala
  src/test/scala/beam/integration/ThreeIterationsSpec.scala
  src/test/scala/beam/integration/ridehail/RideHailTestHelper.scala
  src/test/scala/beam/performance/RouterPerformanceSpec.scala
  src/test/scala/beam/router/WarmStartRoutingSpec.scala
  src/test/scala/beam/sflight/SfLightRunSpec.scala
  src/test/scala/beam/utils/SimRunnerForTest.scala
Labels: review

#1449 fixed random distribution and refactored class UniformVehiclesAdjustment
  src/main/scala/beam/sim/vehicles/UniformVehiclesAdjustment.scala
Labels: review

#1457 reproduce/fix: numberOfVehicles in root folder on production run
  src/main/scala/beam/sim/BeamSim.scala
Labels: review

#1412 remove rounding of the computed delay
  src/main/scala/beam/analysis/DelayMetricAnalysis.scala
Labels: review

#1463 DeadHeadingAnalysis: Should not leak if an exception happens
  src/main/java/beam/analysis/plots/DeadHeadingAnalysis.java
Labels: review

#1465 RealizedModeAnalysis.java: Fix NPE
  src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
Labels: review

#1460 add bike to every household
  src/main/scala/beam/agentsim/agents/vehicles/BeamVehicleType.scala
  src/main/scala/beam/utils/scenario/ScenarioLoader.scala
  test/input/beamville/vehicleTypes.csv
  test/input/sf-light/vehicleTypes-cavs-all.csv
  test/input/sf-light/vehicleTypes-cavs-half.csv
  test/input/sf-light/vehicleTypes-test-energy.csv
  test/input/sf-light/vehicleTypes.csv
Labels: review

#1469 ignoring values with empty values in filePaths
  src/main/scala/beam/utils/ConfigConsistencyComparator.scala
Labels: review

#1466 keep console appender on or off as file logger start
  src/main/java/beam/utils/LoggingUtil.java
  src/main/resources/beam-template.conf
  src/main/scala/beam/router/r5/R5RoutingWorker.scala
  src/main/scala/beam/sim/BeamHelper.scala
  src/main/scala/beam/sim/RunBeam.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
  src/main/scala/beam/utils/ConfigConsistencyComparator.scala
Labels: review

#1470 sync master with sfbay
  src/main/java/beam/utils/LoggingUtil.java
  src/main/resources/beam-template.conf
  src/main/scala/beam/agentsim/agents/vehicles/BeamVehicleType.scala
  src/main/scala/beam/router/r5/R5RoutingWorker.scala
  src/main/scala/beam/sim/BeamHelper.scala
  src/main/scala/beam/sim/RunBeam.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
  src/main/scala/beam/utils/ConfigConsistencyComparator.scala
  src/main/scala/beam/utils/scenario/ScenarioLoader.scala
  test/input/beamville/vehicleTypes.csv
  test/input/sf-light/vehicleTypes-cavs-all.csv
  test/input/sf-light/vehicleTypes-cavs-half.csv
  test/input/sf-light/vehicleTypes-test-energy.csv
  test/input/sf-light/vehicleTypes.csv
Labels: review

#1475 convert logging in DelayMetricAnalysis to ExponentialLazyLogging to r…
  src/main/scala/beam/analysis/DelayMetricAnalysis.scala
Labels: review

#1476 log vehicle types count for each household in scenario
  src/main/scala/beam/sim/BeamHelper.scala
Labels: review

#1481 Scenario: Fixed sampling
  src/main/scala/beam/sim/BeamHelper.scala
  src/main/scala/beam/sim/vehicles/UniformVehiclesAdjustment.scala
  src/main/scala/beam/utils/scenario/ScenarioLoader.scala
Labels: review

#1371 Bl/#1346 write generalized link stats to file
  src/main/resources/beam-template.conf
  src/main/scala/beam/scoring/BeamScoringFunctionFactory.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
Labels: review

#1484 use ExponentialLazyLogging in HouseholdFleetManager
  src/main/scala/beam/agentsim/agents/household/HouseholdFleetManager.scala
Labels: review

#1459 Zn/smart scenarios
  src/main/resources/beam-template.conf
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
  src/main/scala/beam/sim/BeamHelper.scala
  src/main/scala/beam/sim/RideHailFleetInitializer.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
  src/main/scala/beam/sim/population/PopulationAdjustment.scala
  src/main/scala/beam/sim/vehicles/DefaultVehiclesAdjustment.scala
  src/main/scala/beam/sim/vehicles/UniformVehiclesAdjustment.scala
  src/main/scala/beam/sim/vehicles/VehiclesAdjustment.scala
  src/main/scala/beam/utils/scenario/ScenarioLoader.scala
  test/input/beamville/vehicleTypes.csv
  test/input/sf-light/sf-light-0.5k.conf
  test/input/sf-light/sf-light-10k.conf
  test/input/sf-light/sf-light-1k.conf
  test/input/sf-light/sf-light-2.5k.conf
  test/input/sf-light/sf-light-25k.conf
  test/input/sf-light/sf-light-5k.conf
  test/input/sf-light/sf-light.conf
  test/input/sf-light/urbansim-100k.conf
  test/input/sf-light/urbansim-10k-test-energy.conf
  test/input/sf-light/urbansim-10k.conf
  test/input/sf-light/urbansim-1k.conf
  test/input/sf-light/vehicle-energy/2016_AUDI_A3_4cyl_2WD_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_BMW_328d_4cyl_2WD_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_BMW_i3_REx_PHEV_Charge_Depleting_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_BMW_i3_REx_PHEV_Charge_Sustaining_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_CHEVROLET_Malibu_4cyl_2WD_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_CHEVROLET_Spark_EV_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_CHEVROLET_Volt_Charge_Depleting_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_CHEVROLET_Volt_Charge_Sustaining_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_FORD_C-MAX_(PHEV)_Charge_Depleting_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_FORD_C-MAX_(PHEV)_Charge_Sustaining_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_FORD_C-MAX_HEV_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_FORD_Escape_4cyl_2WD_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_FORD_Explorer_4cyl_2WD_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_HYUNDAI_Elantra_4cyl_2WD_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_HYUNDAI_Sonata_PHEV_Charge_Depleting_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_HYUNDAI_Sonata_PHEV_Charge_Sustaining_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_KIA_Optima_Hybrid_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_Leaf_24_kWh_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_Nissan_Leaf_30_kWh_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_TOYOTA_Camry_4cyl_2WD_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_TOYOTA_Corolla_4cyl_2WD_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2016_TOYOTA_Highlander_Hybrid_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2017_CHEVROLET_Bolt_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2017_Prius_Prime_Charge_Depleting_explicitbin_model_only.csv
  test/input/sf-light/vehicle-energy/2017_Prius_Prime_Charge_Sustaining_explicitbin_model_only.csv
  test/input/sf-light/vehicleTypes-cavs-all.csv
  test/input/sf-light/vehicleTypes-cavs-half.csv
  test/input/sf-light/vehicleTypes-test-energy.csv
  test/input/sf-light/vehicleTypes.csv
Labels: review

#1485 fix RealizedModeAnalysis graph
  src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
  src/test/scala/beam/agentsim/agents/ridehail/graph/RealizedModeStatsGraphSpec.scala
Labels: review

#1424 update physsimLinkAverageSpeedPercentage stats
  src/main/java/beam/analysis/physsim/PhyssimCalcLinkSpeedStats.java
Labels: WorkInProgress-DoNotMerge, review

#1493 if network.dat present but physsim network file missing, recreate tha…
  .gitignore
  src/main/scala/beam/router/r5/NetworkCoordinator.scala
  src/main/scala/beam/sim/BeamHelper.scala
  src/main/scala/beam/utils/ConfigConsistencyComparator.scala
  test/input/beamville/physsim-network.xml
  test/input/equil-square/physsim-network.xml
  test/input/sf-light/r5/physsim-network.xml
Labels: review

#1495 fix failing realizedModeStatsGraphSpec test
  src/test/scala/beam/agentsim/agents/ridehail/graph/RealizedModeStatsGraphSpec.scala
Labels: review

#1497 Rw/#1496 print collection sizes
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
  src/main/scala/beam/utils/reflection/ReflectionUtils.scala
Labels: review

#1498 Cs/fix offline rha
  src/main/scala/beam/agentsim/agents/PersonAgent.scala
  src/main/scala/beam/agentsim/agents/ridehail/OutOfServiceVehicleManager.scala
  src/main/scala/beam/agentsim/agents/ridehail/RideHailAgent.scala
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
  src/main/scala/beam/agentsim/agents/ridehail/RideHailModifyPassengerScheduleManager.scala
Labels: review

#1499 Cs/more fixing
  src/main/scala/beam/agentsim/agents/PersonAgent.scala
  src/main/scala/beam/agentsim/agents/ridehail/RideHailAgent.scala
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
Labels: review

#1506 Cs/phev fix
  src/main/scala/beam/agentsim/agents/ridehail/RideHailAgent.scala
  src/main/scala/beam/agentsim/agents/ridehail/RideHailIterationsStatsCollector.scala
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
  src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
Labels: review

#1501 Cluster: Minor fixes
  src/main/scala/beam/router/BeamRouter.scala
  src/main/scala/beam/router/r5/R5RoutingWorker.scala
Labels: review

#1517 cacc pr for master (with cherry pick config discrepancy from production)
  src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
  src/main/java/beam/physsim/jdeqsim/cacc/handler/EventCollector.java
  src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/Hao2018CaccRoadCapacityAdjustmentFunction.java
  src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/RoadCapacityAdjustmentFunction.java
  src/main/java/beam/physsim/jdeqsim/cacc/sim/JDEQSimulation.java
  src/main/java/beam/physsim/jdeqsim/cacc/sim/Road.java
  src/main/java/beam/physsim/jdeqsim/cacc/sim/Vehicle.java
  src/main/resources/beam-template.conf
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
  src/main/scala/beam/agentsim/agents/vehicles/BeamVehicleType.scala
  src/main/scala/beam/physsim/jdeqsim/cacc/CACCSettings.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
  src/main/scala/beam/utils/scenario/ScenarioLoader.scala
  test/input/beamville/beam.conf
  test/input/sf-light/sf-light-1k.conf
Labels: review

#1523 VehicleMilesTraveledAnalysis: Create string only once
  src/main/java/beam/analysis/summary/VehicleMilesTraveledAnalysis.java
Labels: review

#1527 only use cars for ridehail
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
Labels: review

#1487 make writing of skims include all od mode hour combinations
  src/main/scala/beam/agentsim/agents/household/HouseholdCAVScheduling.scala
  src/main/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHail.scala
  src/main/scala/beam/agentsim/agents/ridehail/allocation/PoolingAlonsoMora.scala
  src/main/scala/beam/router/BeamSkimmer.scala
  src/main/scala/beam/sim/BeamMobsim.scala
  src/test/scala/beam/agentsim/agents/household/HouseholdCAVSchedulingTest.scala
  src/test/scala/beam/agentsim/agents/ridehail/graph/RealizedModeStatsGraphSpec.scala
  test/input/beamville/taz-centers.csv
Labels: review

#1530 simple grouping method
  src/main/scala/beam/sim/BeamHelper.scala
Labels: review

#1529 Fix conversion and leave commented link to lane)
  src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
  src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
  src/main/scala/beam/agentsim/agents/vehicles/VehicleEnergy.scala
  src/main/scala/beam/agentsim/events/PathTraversalEvent.scala
  test/input/sf-light/vehicleTypes-test-energy.csv
Labels: review

#1514 added reset to companion object
  src/main/scala/beam/sim/BeamSim.scala
  src/main/scala/beam/utils/MathUtils.scala
  src/main/scala/beam/utils/StuckFinder.scala
  src/main/scala/beam/utils/logging/ExponentialLazyLogging.scala
  src/main/scala/beam/utils/logging/ExponentialLoggerWrapperImpl.scala
Labels: review

#1533 create physsim network utilization graph
  src/main/java/beam/analysis/physsim/PhyssimCalcLinkSpeedStats.java
  src/main/scala/beam/analysis/DelayMetricAnalysis.scala
Labels: review

#1518 zn/ridehail shift adjustment
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
Labels: review

#1534 zn/more ridehail agents
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
Labels: review

#1536 zn/generalized time skims
  src/main/resources/beam-template.conf
  src/main/scala/beam/agentsim/agents/PersonAgent.scala
  src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceLCCM.scala
  src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogit.scala
  src/main/scala/beam/agentsim/agents/modalbehaviors/ModeChoiceCalculator.scala
  src/main/scala/beam/router/BeamSkimmer.scala
  src/main/scala/beam/scoring/BeamScoringFunctionFactory.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
  src/main/scala/beam/sim/population/PopulationAttributes.scala
Labels: review

#1538 replace append with prepend for lists
  src/main/scala/beam/analysis/ParkingStatsCollector.scala
Labels: review

#1541 zn/#1539 rh start at activity locations
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
Labels: review

#1406 changed org.scoverage gradle plugin 2.1.0 -> 2.5.0
  build.gradle
Labels: review

#1519 Metrics: Refactored and fixed unit format
  metrics/grafana/dashboards/beam-dashboard.json
Labels: review

#1545 remove warning for delay metrics analysis
  src/main/scala/beam/analysis/DelayMetricAnalysis.scala
Labels: review

#1546 Zn/#1539 rh start at activity locations
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
Labels: review

#1537 Conversion in static load and based on fuel type
  src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
  src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
  src/main/scala/beam/agentsim/agents/vehicles/VehicleEnergy.scala
  src/main/scala/beam/agentsim/events/PathTraversalEvent.scala
  src/main/scala/beam/sim/common/Range.scala
  test/input/beamville/linkToGradePercent.csv
  test/input/sf-light/r5/linkToGradePercent.csv
  test/input/sf-light/vehicleTypes-test-energy.csv
Labels: review

#1515 undo unwanted replacements of out with outWriter
  src/main/java/beam/agentsim/agents/choice/logit/LatentClassChoiceModel.scala
  src/main/java/beam/analysis/spatialtemporalTAZ/SpatialTemporalTAZVizDataWriter.java
  src/main/java/beam/physsim/jdeqsim/AgentSimPhysSimInterfaceDebugger.java
  src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
  src/main/java/beam/router/r5/profile/BeamMcRaptorSuboptimalPathProfileRouter.java
  src/main/java/beam/utils/ConvertOSMToMATSimNetwork.java
  src/main/java/beam/utils/TravelTimeCalculatorHelper.java
  src/main/java/beam/utils/gtfs/MATSim2GTFS.java
  src/main/java/beam/utils/gtfs/SFBayPT2MATSim.java
  src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceLCCM.scala
  src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
  src/main/scala/beam/agentsim/agents/ridehail/RideHailIterationsStatsCollector.scala
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
  src/main/scala/beam/agentsim/agents/ridehail/RideHailModifyPassengerScheduleManager.scala
  src/main/scala/beam/agentsim/agents/ridehail/RideHailSurgePricingManager.scala
  src/main/scala/beam/agentsim/agents/ridehail/RideHailVehicleManager.scala
  src/main/scala/beam/agentsim/agents/ridehail/TNCIterationStats.scala
  src/main/scala/beam/agentsim/agents/vehicles/PassengerSchedule.scala
  src/main/scala/beam/utils/scripts/PopulationWriterCSV.scala
  src/test/scala/beam/sflight/SfLightRouterTransitSpec.scala
  src/test/scala/beam/sim/BeamWarmStartSpec.scala
Labels: review

#1504 add steps on how to fork beam
  docs/developers.rst
Labels: review

#1531 Bl/#1528 confirm shape produced matches publication 4ci
  src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
  src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/Hao2018CaccRoadCapacityAdjustmentFunction.java
  src/main/resources/beam-template.conf
  src/main/scala/beam/sim/config/BeamConfig.scala
  src/main/scala/beam/utils/FileUtils.scala
Labels: review

#1447 Warm start integrate RouteHistory 4ci
  src/main/scala/beam/router/RouteHistory.scala
  src/main/scala/beam/sim/BeamHelper.scala
  src/main/scala/beam/utils/FileUtils.scala
  src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
  src/test/scala/beam/integration/SingleModeSpec.scala
  src/test/scala/beam/router/RouteHistorySpec.scala
Labels: review

#1551 Project: Minor memory improvements
  src/main/scala/beam/agentsim/events/handling/BeamEventsWriterXML.scala
  src/main/scala/beam/router/osm/TollCalculator.scala
Labels: review

#1555 change average on demand waiting time unit
  src/main/java/beam/analysis/plots/RideHailWaitingAnalysis.java
Labels: review

#1557 change pooling params from config
  src/main/resources/beam-template.conf
  src/main/scala/beam/agentsim/agents/ridehail/allocation/PoolingAlonsoMora.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
Labels: review

#1418 #WIP scoring function updated + code base cleaned up
  .gitignore
  src/main/scala/beam/agentsim/agents/MobilityRequest.scala
  src/main/scala/beam/agentsim/agents/household/FastHouseholdCAVScheduling.scala
  src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala
  src/main/scala/beam/agentsim/agents/household/HouseholdCAVScheduling.scala
  src/main/scala/beam/router/BeamSkimmer.scala
  src/test/scala/beam/agentsim/agents/household/FastHouseholdCAVSchedulingSpec.scala
  src/test/scala/beam/agentsim/agents/household/HouseholdCAVSchedulingTest.scala
Labels: review

#1553 Change additivity to true
  src/main/resources/logback.xml
Labels: review

#1563 add csv for numberOfPassenger graphs
  src/main/java/beam/analysis/plots/passengerpertrip/CarPassengerPerTrip.java
  src/main/java/beam/analysis/plots/passengerpertrip/GenericPassengerPerTrip.java
  src/main/java/beam/analysis/plots/passengerpertrip/IGraphPassengerPerTrip.java
  src/main/java/beam/analysis/plots/passengerpertrip/TncPassengerPerTrip.java
Labels: review

#1556 zn/rh vehicle random seed
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
  src/main/scala/beam/sim/vehicles/DefaultVehiclesAdjustment.scala
  src/main/scala/beam/sim/vehicles/UniformVehiclesAdjustment.scala
  src/main/scala/beam/sim/vehicles/VehiclesAdjustment.scala
  src/main/scala/beam/utils/scenario/ScenarioLoader.scala
Labels: review

#1565 Fix total cost/incentive summary stat
  src/main/java/beam/analysis/summary/PersonCostAnalysis.java
Labels: Competition, review

#1568 sorting disk of requests before filtering by distance
  src/main/scala/beam/agentsim/agents/ridehail/AsyncAlonsoMoraAlgForRideHail.scala
Labels: review

#1570 FastHouseholdCAVSchedulingSpec: Use real BeamService instead of mock
  src/test/scala/beam/agentsim/agents/household/FastHouseholdCAVSchedulingSpec.scala
  src/test/scala/beam/utils/SimRunnerForTest.scala
Labels: review

#1552 Prototype comparison scatterplot #1543
  src/main/resources/beam-template.conf
  src/main/scala/beam/router/BeamSkimmer.scala
  src/main/scala/beam/router/TravelTimeObserved.scala
  src/main/scala/beam/sim/BeamHelper.scala
  src/main/scala/beam/sim/BeamMobsim.scala
  src/main/scala/beam/sim/BeamSim.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
  src/main/scala/beam/utils/GeoJsonReader.scala
  src/main/scala/beam/utils/GeoJsonToGpxConvertor.scala
  src/main/scala/beam/utils/GpxWriter.scala
  src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
  src/test/scala/beam/agentsim/agents/household/FastHouseholdCAVSchedulingSpec.scala
  src/test/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHailSpec.scala
  src/test/scala/beam/agentsim/agents/ridehail/AsyncAlonsoMoraAlgForRideHailSpec.scala
  src/test/scala/beam/integration/SingleModeSpec.scala
Labels: review

#1572 TravelTimeObserved: Write only observed
  src/main/scala/beam/router/TravelTimeObserved.scala
Labels: review

#1573 zn/alternative hh vehicle sampling
  src/main/resources/beam-template.conf
  src/main/scala/beam/sim/config/BeamConfig.scala
  src/main/scala/beam/utils/scenario/ScenarioLoader.scala
Labels: review

#1535 Bl/#1510 cacc graphs 4ci
  src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
  src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/Hao2018CaccRoadCapacityAdjustmentFunction.java
  src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/RoadCapacityAdjustmentFunction.java
  src/main/java/beam/physsim/jdeqsim/cacc/sim/Road.java
Labels: review

#1583 create graph for non arrived agents in average time analysis
  src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java
Labels: review

#1591 fix incentive benefit to agent occasionally exceeds fare
  src/main/scala/beam/agentsim/agents/PersonAgent.scala
Labels: review

#1589 fix calibration runner
  src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
  src/main/scala/beam/calibration/SigoptExperimentData.scala
  src/main/scala/beam/calibration/utils/CreateExperiment.scala
  src/main/scala/beam/calibration/utils/SigOptApiToken.scala
  src/main/scala/beam/sim/BeamHelper.scala
  test/input/beamville/example-calibration/experiment.yml
  test/input/sf-light/sf-light-calibration/experiment.yml
Labels: review

#1594 change others to mixedMode in averageTravelTime graph
  src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java
Labels: review

#1587 Draw lines to compare travel time and observed
  src/main/scala/beam/router/TravelTimeObserved.scala
Labels: review

#1601 UrbanSim: New column name for parcel
  src/main/scala/beam/utils/scenario/urbansim/CsvScenarioReader.scala
  src/main/scala/beam/utils/scenario/urbansim/ParquetScenarioReader.scala
  src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala
  src/test/scala/beam/utils/scenario/urbansim/ParquetScenarioReaderTest.scala
Labels: review

#1600 RideHailManager: `persons` has random access, so change it to array
  src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
Labels: review
