Repository LBNL-UCB-STI/beam, pull requests merged in 2019-04, with the labels that each got.

#1562 Add cacc tests 4ci
  src/main/java/beam/analysis/plots/GraphUtils.java
  src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java
  src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
  src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/Hao2018CaccRoadCapacityAdjustmentFunction.java
  src/main/scala/beam/utils/FileUtils.scala
  src/test/scala/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/Hao2018CaccRoadCapacityAdjustmentFunctionTest.scala
  src/test/scala/beam/sflight/CaccSpec.scala
Labels: review

#1598 Fix scatter plot grid for comparing simulation to real data
  src/main/scala/beam/router/TravelTimeObserved.scala
Labels: review

#1599 Add simulation vs reference gpx file
  src/main/scala/beam/utils/GpxCompareSimulationVsReference.scala
Labels: WorkInProgress-DoNotMerge, review

#1608 UrbanSim: Drop corrupted planElement
  src/main/scala/beam/utils/scenario/Models.scala
  src/main/scala/beam/utils/scenario/ScenarioLoader.scala
  src/main/scala/beam/utils/scenario/ScenarioSource.scala
  src/main/scala/beam/utils/scenario/ScenarioWriter.scala
  src/main/scala/beam/utils/scenario/matsim/MatsimScenarioReader.scala
  src/main/scala/beam/utils/scenario/matsim/MatsimScenarioSource.scala
  src/main/scala/beam/utils/scenario/urbansim/CsvScenarioReader.scala
  src/main/scala/beam/utils/scenario/urbansim/DataExchange.scala
  src/main/scala/beam/utils/scenario/urbansim/ParquetScenarioReader.scala
  src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioReader.scala
  src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala
  src/test/scala/beam/utils/scenario/urbansim/ParquetScenarioReaderTest.scala
Labels: review

#1602 Tools: Tool to generate gpx from the link ids
  src/main/scala/beam/utils/LinkIdsToGpx.scala
Labels: review

#1621 add skims file in warmstart directory
  src/main/bash/warmstart/prep-warmstart-from-run.sh
Labels: review

#1613 skimming energy consumption for passengers
  src/main/scala/beam/agentsim/agents/PersonAgent.scala
  src/main/scala/beam/agentsim/agents/TransitDriverAgent.scala
  src/main/scala/beam/agentsim/agents/household/HouseholdCAVDriverAgent.scala
  src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
  src/main/scala/beam/agentsim/agents/ridehail/RideHailAgent.scala
  src/main/scala/beam/router/BeamSkimmer.scala
  src/test/scala/beam/agentsim/agents/RideHailAgentSpec.scala
  test/input/beamville/r5/tolls.dat
Labels: review

#1625 Update Akka to the latest
  build.gradle
Labels: review

#1615 Changed severity level of log message and removed warnings
  src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala
Labels: review

#1618 #1610 add counts column
  src/main/scala/beam/router/TravelTimeObserved.scala
Labels: review

#1578 1574 - Cleanup analysis (RealizedMode, ModeChosen)
  src/main/java/beam/analysis/plots/BaseModeAnalysis.java
  src/main/java/beam/analysis/plots/GraphsStatsAgentSimEventsListener.java
  src/main/java/beam/analysis/plots/ModeChosenAnalysis.java
  src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
Labels: review

#1596 output generalized link stats
  src/main/scala/beam/scoring/BeamScoringFunctionFactory.scala
  src/main/scala/beam/sim/population/PopulationAttributes.scala
Labels: review

#1628 add bash script to zip and upload iteration to s3 #1627
  src/main/bash/zipRootAndLastIterationAndUploadToS3.sh
Labels: review

#1633 BeamSkimmer: Set default energy to zero if it's missing in CSV
  src/main/scala/beam/router/BeamSkimmer.scala
Labels: review

#1635 handle default vehicle type automation level
  src/main/scala/beam/agentsim/agents/vehicles/BeamVehicleType.scala
  src/main/scala/beam/sim/population/PopulationAttributes.scala
Labels: review

#1607 capture all replanning event count
  src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
  src/test/java/beam/analysis/plots/RealizedModeGraphTest.java
Labels: review

#1645 add iteration to archive name
  src/main/bash/zipRootAndLastIterationAndUploadToS3.sh
Labels: review

#1643 UrbanSim data for sf-light: Fix parcel_id
  test/input/sf-light/urbansim/100k/parcel_attr.csv.gz
  test/input/sf-light/urbansim/100k/parcels.csv.gz
  test/input/sf-light/urbansim/10k/parcel_attr.csv.gz
  test/input/sf-light/urbansim/10k/parcels.csv.gz
  test/input/sf-light/urbansim/1k/parcel_attr.csv.gz
  test/input/sf-light/urbansim/1k/parcels.csv.gz
  test/input/sf-light/urbansim/250k/parcel_attr.csv.gz
  test/input/sf-light/urbansim/250k/parcels.csv.gz
Labels: review

#1603 output private vehicles assigned to households #1571
  src/main/scala/beam/sim/BeamHelper.scala
  src/main/scala/beam/sim/config/BeamConfig.scala
  src/test/scala/beam/integration/EventsFileSpec.scala
Labels: review

#1639 MATSim events: Make sure warnings and errors are logged in file
  src/main/resources/logback.xml
Labels: review

#1640 LoggingEventsManager: Do not propagate errors during the processing of event
  src/main/scala/beam/sim/BeamHelper.scala
  src/main/scala/beam/sim/LoggingEventsManager.scala
Labels: review

#1644 Refactored JDEQSimulation
  build.gradle
  src/main/java/beam/physsim/jdeqsim/cacc/sim/JDEQSimulation.java
Labels: review

#1649 Logging error only in a specific condition
  src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala
Labels: review

#1656 Fixed test description and removed dead code
  src/test/scala/beam/sflight/CaccSpec.scala
Labels: review

#1647 check if request buffer time is less then scheduler parallelism
  src/main/scala/beam/utils/scripts/FailFast.scala
Labels: review

#1549 Project: Use forked matsim
  build.gradle
Labels: WorkInProgress-DoNotMerge, review

#1667 ScalaTest show execution times
  build.gradle
Labels: review

#1661 remove redundant dependencies
  build.gradle
Labels: review

#1686 adding replanning penalty
  src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
  src/main/scala/beam/agentsim/agents/modalbehaviors/ModeChoiceCalculator.scala
  src/main/scala/beam/router/model/EmbodiedBeamLeg.scala
  src/main/scala/beam/router/model/EmbodiedBeamTrip.scala
Labels: review

#1678 Handle the case when split is null
  src/main/scala/beam/sim/common/GeoUtils.scala
  src/main/scala/beam/utils/GpxWriter.scala
  src/main/scala/beam/utils/map/EnvelopeToGpx.scala
  src/main/scala/beam/utils/map/GeoJsonToGpxConvertor.scala
  src/main/scala/beam/utils/map/GpxWriter.scala
  src/main/scala/beam/utils/map/LinkIdsToGpx.scala
  src/main/scala/beam/utils/map/R5NetworkPlayground.scala
Labels: review

#1651 od skimm scatter plot #1611
  src/main/scala/beam/router/TravelTimeObserved.scala
Labels: review

#1679 Zb/mode choice warning fixes
  src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceDriveIfAvailable.scala
  src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceLCCM.scala
  src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
  src/main/scala/beam/agentsim/agents/modalbehaviors/ModeChoiceCalculator.scala
  src/main/scala/beam/replanning/ReplanningUtil.scala
Labels: review

#1694 Use `R5` from `com.github.LBNL-UCB-STI`
  build.gradle
Labels: review

#1695 Use `R5` from `com.github.LBNL-UCB-STI`
  build.gradle
Labels: review

#1478 throw exception if bike is missing in vehicle types and remove default bike
  src/main/scala/beam/agentsim/agents/vehicles/BeamVehicleType.scala
  src/main/scala/beam/utils/scenario/ScenarioLoader.scala
Labels: mergeAfter15April2019, review

#1707 Adjust speeds, highways and other things
  build.gradle
  src/main/java/beam/router/r5/R5MnetBuilder.java
  src/main/scala/beam/router/r5/NetworkCoordinator.scala
  src/main/scala/beam/utils/osm/WayFixer.scala
  src/test/scala/beam/utils/osm/WayFixerTest.scala
Labels: review

#1671 Events: Added linkTravelTime to attributes of PathTraversalEvent
  src/main/scala/beam/agentsim/events/PathTraversalEvent.scala
  src/main/scala/beam/analysis/DelayMetricAnalysis.scala
Labels: review

#1708 Scatter plot should include only car travel time
  src/main/scala/beam/agentsim/agents/PersonAgent.scala
  src/main/scala/beam/router/BeamSkimmer.scala
  src/main/scala/beam/router/TravelTimeObserved.scala
  src/main/scala/beam/router/model/EmbodiedBeamTrip.scala
  src/main/scala/beam/router/r5/R5RoutingWorker.scala
  src/main/scala/beam/sim/BeamServices.scala
  src/main/scala/beam/sim/BeamSim.scala
  src/main/scala/beam/utils/ScenarioComparator.scala
  src/test/scala/beam/agentsim/agents/household/FastHouseholdCAVSchedulingSpec.scala
Labels: review

#1717 Log number of times when min speed has been used during the iteration
  src/main/resources/logback.xml
  src/main/scala/beam/router/BeamRouter.scala
  src/main/scala/beam/router/r5/R5RoutingWorker.scala
  src/main/scala/beam/sim/BeamMobsim.scala
Labels: review

#1704 fix: Motorized vehicle miles traveled should not includes walk
  src/main/java/beam/analysis/summary/VehicleMilesTraveledAnalysis.java
Labels: review

#1718 Add slack notification for beam deployments
  aws/src/main/python/beam_lambda/lambda_function.py
Labels: review

#1722 Fix TravelTimeObserved related tests
  src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
  src/test/scala/beam/utils/TestConfigUtils.scala
Labels: review

#1729 added observerVsSimulated histogram
  src/main/scala/beam/router/TravelTimeObserved.scala
Labels: review

#1736 SimRunnerForTest: Provide TravelTimeObserved for SimRunnerForTest
  src/test/scala/beam/utils/SimRunnerForTest.scala
Labels: review

#1725 Include all modes in excerpt skims
  src/main/scala/beam/router/BeamSkimmer.scala
Labels: review

#1739 Hl/#1709 scaling fuel consumption_v2
  src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
Labels: review

#1742 log activities with non-negative end times
  src/main/scala/beam/sim/BeamSim.scala
Labels: review

#1738 new histogram for all roads
  src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/Hao2018CaccRoadCapacityAdjustmentFunction.java
Labels: review

#1733 add logs to beam skimmer
  src/main/scala/beam/router/BeamSkimmer.scala
Labels: review

#1732 set write matsim network to true by default
  src/main/resources/beam-template.conf
  src/main/scala/beam/sim/config/BeamConfig.scala
Labels: review

#1712 Sync up with master: Part 1
  build.gradle
  src/main/java/beam/router/r5/R5MnetBuilder.java
  src/main/resources/logback.xml
  src/main/scala/beam/agentsim/agents/PersonAgent.scala
  src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
  src/main/scala/beam/router/BeamRouter.scala
  src/main/scala/beam/router/BeamSkimmer.scala
  src/main/scala/beam/router/TravelTimeObserved.scala
  src/main/scala/beam/router/model/EmbodiedBeamTrip.scala
  src/main/scala/beam/router/r5/NetworkCoordinator.scala
  src/main/scala/beam/router/r5/R5RoutingWorker.scala
  src/main/scala/beam/sim/BeamMobsim.scala
  src/main/scala/beam/sim/BeamServices.scala
  src/main/scala/beam/sim/BeamSim.scala
  src/main/scala/beam/utils/ScenarioComparator.scala
  src/main/scala/beam/utils/osm/WayFixer.scala
  src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
  src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
  src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
  src/test/scala/beam/agentsim/agents/household/FastHouseholdCAVSchedulingSpec.scala
  src/test/scala/beam/utils/SimRunnerForTest.scala
  src/test/scala/beam/utils/TestConfigUtils.scala
  src/test/scala/beam/utils/osm/WayFixerTest.scala
Labels: review

#1737 fix beam sim lambda merge issues
  aws/src/main/python/beam_lambda/lambda_function.py
  gradle.properties
Labels: review

#1727 Code cleanup - removed 10 warnings
  src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala
  src/main/scala/beam/utils/reflection/ReflectionUtils.scala
Labels: review

#1746 Fix zip iteration script
  src/main/bash/zipRootAndLastIterationAndUploadToS3.sh
Labels: review

#1745 Fixed `Can' t connect to X11 window server using 'localhost:10.0' as …
  build.gradle
Labels: review

#1747 Changed HouseHoldInfo.cars from Double to Int
  src/main/scala/beam/utils/scenario/Models.scala
  src/main/scala/beam/utils/scenario/matsim/MatsimScenarioReader.scala
  src/main/scala/beam/utils/scenario/urbansim/CsvScenarioReader.scala
  src/main/scala/beam/utils/scenario/urbansim/DataExchange.scala
  src/main/scala/beam/utils/scenario/urbansim/ParquetScenarioReader.scala
  src/test/scala/beam/utils/scenario/urbansim/ParquetScenarioReaderTest.scala
Labels: review

#1716 TravelTime: Use 2-d array (instead of hashmap) to store travel time
  src/main/java/beam/utils/TravelTimeCalculatorHelper.java
  src/main/scala/beam/router/LinkTravelTimeContainer.scala
Labels: review

#1657 Project: Simplified logback initialization
  src/main/java/beam/utils/LoggingUtil.java
  src/main/resources/logback.xml
  src/main/scala/beam/router/r5/R5RoutingWorker.scala
  src/main/scala/beam/sim/BeamHelper.scala
  src/main/scala/beam/utils/ScenarioComparator.scala
Labels: mergeAfter15April2019, review

#1670 R5RoutingApp to be able to make routing request via HTTP Post request
  build.gradle
  src/main/scala/beam/agentsim/scheduler/TriggerMeasurer.scala
  src/main/scala/beam/router/R5RoutingApp.scala
  src/main/scala/beam/sim/BeamWarmStart.scala
  src/main/scala/beam/utils/json/AllNeededFormats.scala
  src/main/scala/beam/utils/json/Format.scala
  src/main/scala/beam/utils/json/IdFormat.scala
  src/main/scala/beam/utils/json/LocationFormat.scala
Labels: review

#1755 Memory optimizations for events writers (CSV, XML)
  src/main/java/beam/agentsim/events/handling/BeamEventsLogger.java
  src/main/scala/beam/agentsim/events/PathTraversalEvent.scala
  src/main/scala/beam/agentsim/events/handling/BeamEventsWriterXML.scala
Labels: review

#1760 fix exclusion syntax for all iterations
  src/main/bash/zipRootAndLastIterationAndUploadToS3.sh
Labels: review

#1762 histogram to check link length distributions within the network
  src/main/java/beam/analysis/physsim/PhyssimNetworkLinkLengthDistribution.java
  src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
Labels: review

#1765 Startup message logged twice 4ci - fixed
  src/main/scala/beam/sim/BeamHelper.scala
  src/main/scala/beam/utils/ConfigConsistencyComparator.scala
Labels: review

#1754 Write csv and plot to compare euclidean vs. length attribute plot #1697
  src/main/java/beam/analysis/physsim/PhyssimNetworkComparisonEuclideanVsLengthAttribute.java
  src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
Labels: review
